repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest tag from the repository
    hooks:
    - id: trailing-whitespace
    - id: check-yaml

-   repo: https://github.com/psf/black
    rev: 24.4.2  # Use the latest tag from the repository
    hooks:
    - id: black

-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2  # Use the latest tag from the repository
    hooks:
    - id: isort
